name: Env Vars
on: [push]

env:
  GLOBAL_VAR: global

jobs:
  show:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: job
    steps:
      - env:
          STEP_VAR: step
        run: |
          echo $GLOBAL_VAR
          echo $JOB_VAR
          echo $STEP_VAR
