name: Show Repository Code
on: [push]

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show files
        run: ls -lah

      - name: Show README
        run: cat README.md
